server:
  port: 8007

# mybatis 配置
mybatis:
  type-aliases-package: com.cmic.hbservice.domain


spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.66.24:3306/hb?serverTimezone=UTC
    username: root
    password: password

huobi:
  exchange:
    url: https://www.huobi.co/zh-cn/exchange/?s=
  api:
    url: https://api.huobi.br.com
  key:
    path: c:/src/keys/hb.json

logging:
  file: hb.log
  level:
    root: info